WRR-12002: Add performance tests for new Color Picker component
enactjs/performance-tests pull request #102
Opened 2024-12-11 14:31 UTC by adrian-cocoara-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] I have run automated testing and it is passed
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Added performance tests for new Color Picker Component

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added performance tests for new Color Picker Component

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRR-12002

### Comments

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

2025-01-17 10:33 UTC, stanca-pop-lgp requested changes

2025-01-17 10:33 UTC, stanca-pop-lgp commented on performance/tests/sandstone/ColorPicker.test.js
> +const {CLS, PageLoadingMetrics, FPS, getAverageFPS} = require('../../TraceModel');
```suggestion
const {CLS, FPS, getAverageFPS, PageLoadingMetrics} = require('../../TraceModel');
```

2025-01-17 10:41 UTC, stanca-pop-lgp approved these changes
LGTM

2025-02-10 07:21 UTC, MikyungKim commented
@stanca-pop-lgp , Should we keep this PR or close if the component is private?

2025-02-10 08:27 UTC, stanca-pop-lgp commented
> @stanca-pop-lgp , Should we keep this PR or close if the component is private?

We should close it. Thank you!

2025-02-10 08:27 UTC, closed without merging