WRQ-4709 : Added performance tests for agate components
enactjs/performance-tests pull request #79
Opened 2024-01-15 15:05 UTC by daniel-stoian-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Added performance tests for agate components

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-4709

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com

2024-01-22 12:18 UTC, stanca-pop-lgp requested changes
Great job! Effort appreciated.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/DateTimePicker.js
> +import kind from '@enact/core/kind';
Please sort imports.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/Drawer.js
> +import Button from "@enact/agate/Button";
Please use single quotes for imports.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/Dropdown.js
> +import kind from '@enact/core/kind';
Please sort imports.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/Icon.js
> +import kind from '@enact/core/kind';
Please use agate/Icon and sort imports.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/LabeledIcon.js
> +		<LabeledIcon
Please sort props.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/LabeledIconButton.js
> +		<LabeledIconButton
Please sort props.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/MediaPlayer.js
> +import kind from '@enact/core/kind';
Please sort imports.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/Panels.js
> +import TabGroup from "@enact/agate/TabGroup";
Please use single quotes for imports.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/Picker.js
> +		<Picker id="picker" title="Picker Default" >{pickerList}</Picker>
Please remove empty space after title prop value.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/PopupMenu.js
> +				open={open}
Please sort props.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/RangePicker.js
> +			defaultValue={0}
Please sort props.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/Scroller.js
> +		<div style={{height: '700px'}} id="scroller">
Please sort props.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/Slider.js
> +			<Slider id="slider" min={0} max={100} defaultValue={0} />
Please sort props.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/TimePicker.js
> +		<TimePicker id="timePicker"	/>
Please leave a single empty space before closing tag.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/ToggleButton.js
> +			toggleOnLabel="On"
Please sort props.

2024-01-22 12:18 UTC, stanca-pop-lgp commented on src/views/agate/VirtualList.js
> +					dataSize={dataSizeProp}
Please sort props.

2024-01-22 15:13 UTC, stanca-pop-lgp approved these changes

2024-02-01 08:01 UTC, seunghoh approved these changes

2024-02-01 08:01 UTC, merged